# https://practical.li/clojure/continuous-integration/github-actions/
name: Tests build
on: [push, pull_request]
jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: 1.10.1.693 # Clojure CLI based on tools.deps

      - name: Run Clj Unit tests
        run: make test-clj

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Cljs Unit tests
        run: make test-cljs-shadow

      - name: Install babashka master
        run: bash <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

      - name: Run bb tests
        run: bb test
